### PR TITLE
Add include and exclude options and update packages

### PR DESCRIPTION
**Pull request by MaximStone**
I faced a strong need to exclude some files from plugin scope and I had to fork the plugin. I suppose it could be nice upgrade for the plugin if you will.

Thanks!

### CODE REVIEW

**Comment by vatson** [comment]
Hello @MaximStone.

It looks very useful. Great job! 

Could you please update README.md with the appropriate description so that others know about these options?

Thank you

**Comment by MaximStone** [comment]
Sure! Thanks for the feedback.

**Comment by MaximStone** [comment]
@vatson Hi! Please take a look. Is it ok?

**Comment by vatson** [comment]
Yeah. Everything is ok. I'll just update version to 0.3.0 according semver recommendations and then release it.

**Comment by MaximStone** [comment]
@vatson Could you publish it to npm registry? Thanks!

**Pull request merged**
